services:
  deku:
    image: mizle/deku:latest
    container_name: deku
    volumes:
      - ./database:/database
    platform: linux/amd64
    ports:
      - 4000:3000
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - CRYPT_KEY=${CRYPT_KEY}
    restart: unless-stopped
    healthcheck:
      test: [CMD, curl, -f, 'http://127.0.0.1:3000/server/healthcheck']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
